### ISSUE TITLE
Opening trade on first bar if there were no ticks before causes incorrect profit.

### ISSUE THREAD

**Issue by Joearrowsmith** [nuric/pedlar#1]
![image](https://user-images.githubusercontent.com/32938430/51793698-6e52d000-21bc-11e9-9e54-d0a4514e1f8e.png)
![image](https://user-images.githubusercontent.com/32938430/51793700-76ab0b00-21bc-11e9-981d-90541111ef34.png)

As there was no tick before it causes the price of the bar to be set to zero which causes a huge change in profit when order is closed.

**Comment by nuric** [comment]
True, backtesting uses the ticks to compute the price difference and that is updated when a tick is received. I can see only one fix and that is to stop orders from being placed if we don't have tick data which only occurs if the first event is a `on_bar`. We can't use the bar information because the bar only tells about either the bid or the ask, whereas we need both.
